export const enum ChatType {
    AZURLANE_SHIP = 'al-ship',
    AFREECA = 'afreeca',
    BOOK = 'book',
    CRUSADERQUEST_HERO = 'cq-hero',
    IMAGE = 'image',
    KAKAO_CLIP = 'kakao-clip',
    LINK = 'link',
    LOL_CHAMPION = 'champion',
    LOL_USER = 'lol-user',
    MAGIC_CONCH = 'magic-conch',
    SERIOUS = 'serious',
    STREAM = 'stream',
    TEXT = 'text',
    TWITCH = 'twitch',
    TWITCH_CLIP = 'twitch-clip',
    YOUTUBE = 'youtube',
}
