export const enum ChatType {
    AZURLANE_SHIP = 'al-ship',
    AFREECA = 'afreeca',
    ANIMATION = 'animation',
    BOOK = 'book',
    CHARACTER_VOICE = 'character-voice',
    CRUSADERQUEST_HERO = 'cq-hero',
    GIRLS_FRONTLINE_DOLL = 'gf-doll',
    IMAGE = 'image',
    KAKAO_CLIP = 'kakao-clip',
    LINK = 'link',
    MOVIE = 'movie',
    LOL_CHAMPION = 'champion',
    LOL_USER = 'lol-user',
    MAGIC_CONCH = 'magic-conch',
    SERIOUS = 'serious',
    STREAM = 'stream',
    TEXT = 'text',
    TWITCH = 'twitch',
    TWITCH_CLIP = 'twitch-clip',
    YOUTUBE = 'youtube',
}
